# Generic subclasses of minister (not explicitly related to a state or region)

SELECT ?position ?positionLabel ?positionDescription (GROUP_CONCAT(DISTINCT(?altLabel); SEPARATOR="\n") AS ?alias) {
  ?position wdt:P279+ wd:Q83307 .
  FILTER NOT EXISTS { ?position wdt:P17 ?country }    # not country-specific
  FILTER NOT EXISTS { ?position wdt:P1308 ?person }   # not held by specific person
  FILTER NOT EXISTS { ?position wdt:P571 ?date }      # not created at specific date
  FILTER NOT EXISTS { ?position wdt:P1001 ?region }   # not belonging to specific region
  OPTIONAL { ?position skos:altLabel ?altLabel . FILTER (lang(?altLabel) = "en") }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} GROUP BY ?position ?positionLabel ?positionDescription
